[platformio]
default_envs = pico2_official_sdk
src_dir = pio_stub

[env:pico2_official_sdk]
platform = native
extra_scripts = extra_scripts/pico_sdk_tasks.py
monitor_speed = 115200
monitor_filters = time

; These are consumed by extra_scripts/pico_sdk_tasks.py.
custom_pico_board = pico2
custom_build_dir = build-pio
custom_firmware_name = vix_base_pico2_controller.uf2
